### ISSUE TITLE
返回了SUCCESS，但实际并未签到

### ISSUE THREAD

**Issue by Mmahaha** [thriving123/fuckTodayStudy#1]
感谢作者，前段时间正常奔放，今天出现异常
执行的是autoSign任务，在submitForm()后打印返回信息无异常，在APP中查看依旧未签到
```java
res = self.session.post(f'{self.host}wec-counselor-sign-apps/stu/sign/submitSign', headers=headers,
                                data=json.dumps(self.form), verify=False).json()
        print(str(res))
        return res['message']
```

![image](https://user-images.githubusercontent.com/42790539/115100134-51f20800-9f6d-11eb-8929-90aeb65fcde1.png)

**Comment by thriving123** [comment]
已经更新修复了，建议您下载最新版，另外 邮件推送的域名正在重新备案，所以无法使用，您可以使用自己的推送方式，或者取消推送，又或者把debug改为false以忽略报错，您可以加群：1053970959以及时反馈问题，谢谢

**Comment by Mmahaha** [comment]
> 已经更新修复了，建议您下载最新版，另外 邮件推送的域名正在重新备案，所以无法使用，您可以使用自己的推送方式，或者取消推送，又或者把debug改为false以忽略报错，您可以加群：1053970959以及时反馈问题，谢谢

收到，感谢~
