### ISSUE TITLE
我在服务器上运行代码没问题，但是用crontab就有问题了

### ISSUE THREAD

**Issue by iodjjd** [thriving123/fuckTodayStudy#11]
Oct  3 11:59:02 v032f_00385274 CROND[41177]: (root) CMD (python3  /usr/games/fuck/wan/index.py)
Oct  3 11:59:06 v032f_00385274 CROND[41176]: (root) CMDOUT (Traceback (most recent call last):)
Oct  3 11:59:06 v032f_00385274 CROND[41176]: (root) CMDOUT (  File "/usr/games/fuck/wan/index.py", line 101, in <module>)
Oct  3 11:59:06 v032f_00385274 CROND[41176]: (root) CMDOUT (    main())
Oct  3 11:59:06 v032f_00385274 CROND[41176]: (root) CMDOUT (  File "/usr/games/fuck/wan/index.py", line 21, in main)
Oct  3 11:59:06 v032f_00385274 CROND[41176]: (root) CMDOUT (    config = getYmlConfig())
Oct  3 11:59:06 v032f_00385274 CROND[41176]: (root) CMDOUT (  File "/usr/games/fuck/wan/index.py", line 13, in getYmlConfig)
Oct  3 11:59:06 v032f_00385274 CROND[41176]: (root) CMDOUT (    file = open(yaml_file, 'r', encoding="utf-8"))

**Comment by iodjjd** [comment]
> Oct 3 11:59:02 v032f_00385274 CROND[41177]: (root) CMD (python3 /usr/games/fuck/wan/index.py) Oct 3 11:59:06 v032f_00385274 CROND[41176]: (root) CMDOUT (Traceback (most recent call last):) Oct 3 11:59:06 v032f_00385274 CROND[41176]: (root) CMDOUT ( File "/usr/games/fuck/wan/index.py", line 101, in ) Oct 3 11:59:06 v032f_00385274 CROND[41176]: (root) CMDOUT ( main()) Oct 3 11:59:06 v032f_00385274 CROND[41176]: (root) CMDOUT ( File "/usr/games/fuck/wan/index.py", line 21, in main) Oct 3 11:59:06 v032f_00385274 CROND[41176]: (root) CMDOUT ( config = getYmlConfig()) Oct 3 11:59:06 v032f_00385274 CROND[41176]: (root) CMDOUT ( File "/usr/games/fuck/wan/index.py", line 13, in getYmlConfig) Oct 3 11:59:06 v032f_00385274 CROND[41176]: (root) CMDOUT ( file = open(yaml_file, 'r', encoding="utf-8"))

**Comment by thriving123** [comment]
先cd到主路径
 后python index.py
