### ISSUE TITLE
logic error or not

### ISSUE THREAD

**Issue by cyantau** [thriving123/fuckTodayStudy#16]
file: ./login/casLogin.py
line in: 52~64

```python
52:    if self.type == 0:
            salt = soup.select("#pwdDefaultEncryptSalt")
        else:  # self.type = 1
            salt = soup.select("#pwdEncryptSalt")
        if len(salt) != 0:
            salt = salt[0].get('value')
        else:
            pattern = '\"(\w{16})\"'
            salt = re.findall(pattern, html)
            if (len(salt) == 1):
                salt = salt[0]
            else:
64:             salt = False
```

> if (len(salt) == 1):
                salt = salt[0] </span>

When setting the value of **salt**, you can't ensure  it if this happened like below.

![image](https://user-images.githubusercontent.com/78191624/136687887-f2deb40e-afd8-46e2-848b-b56f7e8f8a19.png)

**Comment by cyantau** [comment]
different school has different  login website, so this could be a little bit different in code. The template in this project can't solve all, that's it.

**Comment by thriving123** [comment]
you can see the latest version and confirm it what is resolved

**Comment by thriving123** [comment]
打算提供免费打卡平台中
