### ISSUE TITLE
henu错误返回码401

### ISSUE THREAD

**Issue by Thegallophorse** [thriving123/fuckTodayStudy#17]
<img width="480" alt="屏幕截图 2021-10-11 194151" src="https://user-images.githubusercontent.com/52592395/136784512-a6f5157f-874a-4d17-8f39-70f55dde0a66.png">

**Comment by Thegallophorse** [comment]
任然存在


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thriving123/fuckTodayStudy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月26日(星期二) 晚上11:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thriving123/fuckTodayStudy] henu错误返回码401 (#17)





 
这是教务系统的问题，现在还有吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by thriving123** [comment]
加我Q，config发我

**Comment by thriving123** [comment]
打算提供免费打卡平台中
