### ISSUE TITLE
GetYaml()函数执行目录问题

### ISSUE THREAD

**Issue by HongjieCN** [thriving123/fuckTodayStudy#24]
比如我从/root目录运行/jrxy/index.py 那么会获取/root目录下的config.yml而不是与index.py同目录的config.yml

**Comment by IceTiki** [comment]
执行脚本时，请先用cd指令切换路径到代码文件夹，然后再用python运行index.py。

**Comment by IceTiki** [comment]
请用

cd 代码文件夹路径
python index.py

而不是

python 代码文件夹路径/index.py

**Comment by IceTiki** [comment]
还有一种方法，在index.py中
在脚本顶部加上一行
import os
在main()函数的第一行加上
os.chdir(os.path.dirname(__file__))  # 将工作路径设置为脚本位置

**Comment by thriving123** [comment]
楼上已修复，请检查无误后关闭issue
