### ISSUE TITLE
『需求』求加湖北文理学院

### ISSUE THREAD

**Issue by XiuerFang** [thriving123/fuckTodayStudy#29]
谢谢大佬！！！

**Comment by thriving123** [comment]
已添加 请测试是否正常

**Comment by XiuerFang** [comment]
『账号密码』
请问智慧校园账号密码是指什么，我使用今日校园学号和密码无法登录
![image](https://github.com/thriving123/fuckTodayStudy/assets/76574728/0a48ba57-ffb2-42ae-bc10-70a43a5f67bc)

**Comment by thriving123** [comment]
今日校园使用学工号登录那里的账号密码
如果确实无法登录请联系我并提供个账号密码以排查问题

**Comment by thriving123** [comment]
已完成湖北文理学院的登录
