### ISSUE TITLE
 [需求]求加贵州商学院

### ISSUE THREAD

**Issue by Sinclair2233** [thriving123/fuckTodayStudy#30]
如上，请问能加上贵州商学院的宿舍考勤吗

**Comment by thriving123** [comment]
已添加 请测试是否正常 有问题及时反馈

**Comment by thriving123** [comment]
请问是否正常 如果正常那么我关闭这个is了

**Comment by Sinclair2233** [comment]
谢谢大佬，但是我今天刚到学校，准备注册测试查看，却被告知原来的邀请码：IT之星YYDS 已过期或达到最大邀请次数，没法注册登录，请问有其他邀请码吗

**Comment by thriving123** [comment]
邀请码非必填
