### ISSUE TITLE
填写成功后邮件发送问题

### ISSUE THREAD

**Issue by ruoli07** [thriving123/fuckTodayStudy#4]
# 邮件发送失败，是什么问题？
![image](https://user-images.githubusercontent.com/65734378/130772418-4a625cfb-a7aa-4646-a4c7-d1fadc4d03e4.png)

**Comment by thriving123** [comment]
方便的话加我qq，在文档里顶部有。你这个问题不太清楚。需要你详细展示一下呢

**Comment by ruoli07** [comment]
sorry ，sendtype 填错了

**Comment by thriving123** [comment]
ok，起飞🛫
