### ISSUE TITLE
今日校园更新了“今日所在地”的表，要怎么改表单的value？

### ISSUE THREAD

**Issue by ruoli07** [thriving123/fuckTodayStudy#5]
## 如图，新加了个详细地址框，虽然不填也可以，但要怎样才能填上？
![value填写](https://user-images.githubusercontent.com/65734378/130773267-42daad3e-94da-44cb-9a7c-5c0763660465.jpg)

**Comment by thriving123** [comment]
多加一个斜杠即可
省/市/区/详细地址
