### ISSUE TITLE
用了lz的阿里云测试方法后报错，腾讯云没有问题

### ISSUE THREAD

**Issue by iodjjd** [thriving123/fuckTodayStudy#6]
![image](https://user-images.githubusercontent.com/76802920/132969835-a1fda1b3-2054-4bc0-9179-0a27b869a9a4.png)

![image](https://user-images.githubusercontent.com/76802920/132969885-07a9f889-b192-4afc-bb2e-64cca17b2790.png)

我把整个依赖库解压到文件夹出问题，但是单独放在一个文件夹没有问题

上传到阿里云之后直接出问题

![image](https://user-images.githubusercontent.com/76802920/132969910-54da06f2-2e3e-433d-ace6-32ddfdc30b24.png)

**Comment by iodjjd** [comment]
文字版：依赖库直接整个文件夹放在本地的效果：

C:\Users\Administrator\Desktop\fuckTodayStudy-main - 副本>python index.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\fuckTodayStudy-main - 副本\index.py", line 5, in <module>
    from todayLoginService import TodayLoginService
  File "C:\Users\Administrator\Desktop\fuckTodayStudy-main - 副本\todayLoginService.py", line 7, in <module>
    from login.Utils import Utils
  File "C:\Users\Administrator\Desktop\fuckTodayStudy-main - 副本\login\Utils.py", line 9, in <module>
    from Crypto.Cipher import AES

阿里云的效果：
{
   "errorMessage": "Module '/code/index.js' is missing.",
   "errorType": "Error",
   "stackTrace": [
      "Error: Module '/code/index.js' is missing."
   ]
}

**Comment by thriving123** [comment]
为啥你的阿里云的运行环境选择了js的运行环境呢？这是python的脚本的呀………………

**Comment by iodjjd** [comment]
![image](https://user-images.githubusercontent.com/76802920/133006952-8be995ce-ee77-452f-a5e9-bb0172fc1d03.png)

**Comment by iodjjd** [comment]
一个新发现：俺把腾讯云能够签到的代码下载到本地，再把本地的文件上传到阿里云竟然能运行。。。这是俺上传到阿里云的压缩包，可以给大家参考下，（删去了 config.yml 和 sign.jpg 文件，请自行添加）
[li.zip](https://github.com/thriving123/fuckTodayStudy/files/7152744/li.zip)

**Comment by iodjjd** [comment]
在阿里云运行
`pip3 install -r ./src/requirements.txt -t ./src -i https://mirrors.aliyun.com/pypi/simple`
直接报错

**Comment by iodjjd** [comment]
### 为啥你的阿里云的运行环境选择了js的运行环境呢？这是python的脚本的呀………………

换了python运行环境一样报错，不管是用腾讯云的办法还是您的方法一样报错，本地方法都尝试了

**Comment by thriving123** [comment]
换python环境报错肯定是其他报错原因，但是你没有贴出来。至于依赖问题，本来依赖都是一样的，只是腾讯云可以通过pip安装，而阿里云的新版客户端好像还有一定的bug而无法直接安装，因此阿里云需要下载dependency.zip的依赖包一并打包提交。而你通过腾讯云下载的代码包，是已经在腾讯云通过pip安装配置好了的依赖包，原理其实和下载dependency.zip依赖包一并打包上传性质是一样的。
