### ISSUE TITLE
小小吐槽一下

### ISSUE THREAD

**Issue by JMFANS** [thriving123/fuckTodayStudy#7]
`[2021-09-25` 01:22:34]
第1个配置出错了
表单未找到你设置的值：36-37.2°c
，你上次系统选的值为：36~37.2℃
`
如果重复运行的话能不能返回“已签到”的形式呢，虽然这并非必要

**Comment by thriving123** [comment]
你这很明显是值写错了

然后重复签到/信息收集等得到的返回值都是今日校园返回的而不是我返回的。

也没有仔细去抓包分析首次提交和更新返回的内容是否是完全一致的
