### ISSUE TITLE
如何执行多次签到任务？

### ISSUE THREAD

**Issue by real-hao** [thriving123/fuckTodayStudy#8]
如何在某触发时间点在某个账号下执行2次签到任务(`某时刻任务列表里有多项的情况`)？

**Comment by thriving123** [comment]
这个功能暂时没有实现，如果你会一点python的话去到autoSign.py里的38行里可以看到最后有个[0]
其中的0就是控制是第几个签到任务。0代表第1个。1代表第二个，以此类推
